sudo: required
services:
  - docker

before_install:
  - docker build -t yyyttthan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yyyttthan/docker-react npm run test

language: generic 